### ISSUE TITLE
Items display their id, rather than their user-readable name

### ISSUE THREAD

**Issue by cosmo-naut** [IsolatedLun/PzCompare-Build#3]
Should be "Hattori Hanzo Katana" or whatever instead of 'KillBill', this will allow non-dev users to use the applet easily

**Comment by cosmo-naut** [comment]
It seems like the z is not being set correctly for some of these items
![image](https://user-images.githubusercontent.com/30992774/175174794-8a521185-2407-450d-9420-13b19bab407f.png)
My best guess is that either there's an error in the parser, or the format for some items is inconsistent. I haven't taken a look at the parser yet though, just gathering information..

**Comment by IsolatedLun** [comment]
It was an error in the parser, since the DisplayName of the item is sometimes multiple words the parser just ignored it. (it uses regex)

**Comment by IsolatedLun** [comment]
I completely fixed this issue by just making the key an object it's DisplayName, instead of over complicating everything and having separate names!
