### ISSUE TITLE
Opening dictionary in new tab shows a 404

### ISSUE THREAD

**Issue by cosmo-naut** [IsolatedLun/PzCompare-Build#5]

**Comment by IsolatedLun** [comment]
Since I'm using a free version of heroku the app is not always online, so opening the app with any path that is not "/" will result to it not loading, I can't fix it on my end. :(

**Comment by cosmo-naut** [comment]
I guess potential solutions are:
- Pay for hosting
- Change to another free host that supports the feature

For now though, no need to change
