### ISSUE TITLE
Is this project open to contributions?

### ISSUE THREAD

**Issue by cosmo-naut** [IsolatedLun/PzCompare-Build#7]
Hi, I figured I should actually ask for permission before I go and start sending you PRs :)

I like this project, and it would be a really good way for me to practice web dev, I also love Zomboid and think this tool could be really useful.

If you dislike any of my changes/proposals, please let me know what you dislike about them and I'm happy to accomodate.

I respect that this is your project, I don't want to 'take over' or step on your toes at all, I'd just love to help out.

Do you have any style guidelines, or a code formatter?
I was messing around in the file but my prettier altered a lot of lines, perhaps you could add your prettier configuration as a `.prettierrc` file so that my changes are as minimal as possible
https://prettier.io/docs/en/configuration.html

**Comment by IsolatedLun** [comment]
Sure thing man, I'm adding comments so that you can understand the code more :), and yes I added the prettier file too.

Feel free to ask any question too!
