### ISSUE TITLE
User should be able to filter dropdown list of items by whether they have certain categories

### ISSUE THREAD

**Issue by cosmo-naut** [IsolatedLun/PzCompare-Build#9]
For example, user should be able to add filters such as:

- Guns that fire a certain ammo type
- Clothing that fits on the legs
- Is a container

This will require a rewrite of how the dropdown list actually gets those item names.
I'm happy to take a look at it and see if I can come up with something clever.

Thoughts? @IsolatedLun

**Comment by cosmo-naut** [comment]
Filter by mod would be good too

**Comment by IsolatedLun** [comment]
Hey, sorry for the late response! 

I have implemented something like this in an old project, so I'll integrate that logic here soon.
And yes feel free to implement your own ideas!
